- hosts: all
  tasks:
    - name: copy artifact
      copy:
        src:'multygo_master'
        dest: /home/vagrant/simple
        mode: 0777

    - name: create simple service template
      become: true
      template:
        src: simple.service.j2
        dest: /etc/systemd/system/simple.service

    - name: start systemd service
      become: true
      systemd:
        name: simple
        daemon_reload: yes
        enabled: true
        state: restarted
